### PR TITLE
Added grammar for Java EE Expression Language in xhtml files.

### PR DESCRIPTION
**Pull request by per-steinar**
I have made some changes to how the EL grammar is injected. This PR does NOT define JSF as a separate language. Instead it injencts the grammar into HTML/XHTML files and any other extension that are activated, shoud continue to be activated. Please do test this before merging to ensure it is behaving as you wish.

### CODE REVIEW

**Comment by leosj29** [comment]
For some reason, when testing these changes, the self-closing tag feature of the other previously mentioned component is disabled.

**Comment by per-steinar** [comment]
I have created a separate

**Comment by per-steinar** [comment]
I have reproduced the issue with the "Auto Close Tag" extension in a simple HTML-only project and disabled all other extenions. It looks to be an issue with that particular extension. If I disable that extension and ensure that the build-in support for autoclosing HTML tags is enabled ("html.autoClosingTags": true), tags autocloses as expected. The "Auto Close Tag" extension has not been updated since 2017 and there are a lot of open issues regarding slow response. This is probably since the functionality is now built into vscode. Please disable that extension and check if tags autocloses as expected.

**Comment by per-steinar** [comment]
@leosj29 Any possibility that you can take a look at this? It should address all of your concerns. The only drawback is that the grammars injects into the default HTML-grammar, but I have not had any issues with it.

**Pull request merged**
